version: '3'

services:
  diaryapp:
    container_name: diaryapp.jar
    image: diaryapp
    restart: always
    build: ./
    ports:
      - "5555:5555"
    networks:
        - registerloginapp_diary-network
networks:
  registerloginapp_diary-network:
    external: true