package com.eneskasikci.diaryapp.requests;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.Id;

@Data
@ApiModel(value = "Post Create Request", description = "DTO for the Post Create Request. " +
        "These are the accessible parameters for the API Requests.")
public class PostCreateRequest {
    @Id
    @ApiModelProperty(value = "Post ID. Automatically generated by the database.")
    private Long request_diaryId;
    @ApiModelProperty(value = "Post Title. Cannot be empty.")
    private String request_diaryTitle;
    @ApiModelProperty(value = "Post Content. Cannot be empty.")
    private String request_diaryContent;
    @ApiModelProperty(value = "Username of the owner. Cannot be empty. It is used to identify the user.")
    private String request_userName;
    @ApiModelProperty(value = "User ID. It is used to identify the user.")
    private Long request_diaryUserId;
}
