package com.eneskasikci.diaryapp.requests;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.Id;

@Data
@ApiModel(value = "Post Update Request", description = "DTO for the Post Update Request. " +
        "These are the accessible parameters for the API Requests.")
public class PostUpdateRequest {
    @Id
    @ApiModelProperty(value = "Post ID. Automatically generated by the database.")
    private Long request_diaryUpdatedPostId;
    @ApiModelProperty(value = "Post Title. Cannot be empty.")
    private String request_diaryUpdatedPostTitle;
    @ApiModelProperty(value = "Post Content. Cannot be empty.")
    private String request_diaryUpdatedPostContent;
    @ApiModelProperty(value = "Username of the owner. Cannot be empty. It is used to identify the user" +
            "and to check if the user is the owner of the post.")
    private String request_diaryUpdatedPost_userName;

}