package com.eneskasikci.diaryapp.responses;

import com.eneskasikci.diaryapp.model.DiaryPosts;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiOperation;
import lombok.Data;

@Data
//@ApiModel(value = "Post Response Model", description = "DTO for the Post Response. " +
//        "These are the accessible parameters for the API Responses." +
//        "We are returning only the necessary information to the user.")
public class PostResponse {
    @ApiModelProperty(value = "Post ID. Automatically generated by the database.")
    private Long response_diaryId;
    @ApiModelProperty(value = "User ID of the owner. Automatically generated by the database.")
    private Long response_diaryUserId;
    @ApiModelProperty(value = "Username of the owner.")
    private String response_userName;
    @ApiModelProperty(value = "Post Title.")
    private String response_diaryTitle;
    @ApiModelProperty(value = "Post Content.")
    private String response_diaryContent;

    public PostResponse (DiaryPosts entity){
        this.response_diaryId = entity.getDiaryId();
        this.response_diaryUserId = entity.getDiaryUsers().getUserId();
        this.response_userName = entity.getDiaryUsers().getUserName();
        this.response_diaryTitle = entity.getDiaryTitle();
        this.response_diaryContent = entity.getDiaryContent();
    }

}
